"""initial schema

Revision ID: 1c779d205bda
Revises:
Create Date: 2026-07-27 23:05:36.117033
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "1c779d205bda"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exchange_rate_cache",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("base_currency", sa.String(length=3), nullable=False),
        sa.Column("quote_currency", sa.String(length=3), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("rate", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("rate_date", sa.Date(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw_response_json", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "base_currency", "quote_currency", "provider", "rate_date", name="uq_fx_rate"
        ),
    )
    with op.batch_alter_table("exchange_rate_cache", schema=None) as batch_op:
        batch_op.create_index(
            "ix_fx_lookup",
            ["base_currency", "quote_currency", "provider", "rate_date"],
            unique=False,
        )

    op.create_table(
        "projects",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("current_step", sa.String(length=32), nullable=False),
        sa.Column("raw_location_input", sa.Text(), nullable=True),
        sa.Column("resolved_latitude", sa.Float(), nullable=True),
        sa.Column("resolved_longitude", sa.Float(), nullable=True),
        sa.Column("monthly_consumption_kwh", sa.Float(), nullable=True),
        sa.Column("selected_system_size_kwp", sa.Float(), nullable=True),
        sa.Column("analysis_status", sa.String(length=32), nullable=False),
        sa.Column("analysis_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pvgis_cache",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("cache_key", sa.String(length=255), nullable=False),
        sa.Column("response_json", sa.JSON(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("pvgis_cache", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_pvgis_cache_cache_key"), ["cache_key"], unique=True)

    op.create_table(
        "chat_messages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("step", sa.String(length=32), nullable=True),
        sa.Column("parser_source", sa.String(length=16), nullable=True),
        sa.Column("payload_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("chat_messages", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_chat_messages_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "proposals",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("share_token", sa.String(length=64), nullable=False),
        sa.Column("requested_system_size_kwp", sa.Float(), nullable=False),
        sa.Column("feasible_system_size_kwp", sa.Float(), nullable=False),
        sa.Column("requested_panel_count", sa.Integer(), nullable=False),
        sa.Column("panel_count", sa.Integer(), nullable=False),
        sa.Column("annual_production_kwh", sa.Float(), nullable=False),
        sa.Column("annual_savings_eur", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("original_capex_usd", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("converted_capex_eur", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("exchange_rate", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("exchange_rate_date", sa.Date(), nullable=False),
        sa.Column("exchange_rate_source", sa.String(length=32), nullable=False),
        sa.Column("exchange_rate_provider", sa.String(length=32), nullable=False),
        sa.Column("payback_years", sa.Float(), nullable=True),
        sa.Column("proposal_data_json", sa.JSON(), nullable=False),
        sa.Column("layout_snapshot_path", sa.String(length=512), nullable=True),
        sa.Column("ai_summary", sa.Text(), nullable=True),
        sa.Column("capacity_warning", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("proposals", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_proposals_project_id"), ["project_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_proposals_share_token"), ["share_token"], unique=True)

    op.create_table(
        "proposal_views",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("proposal_id", sa.String(length=36), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("referrer", sa.String(length=512), nullable=True),
        sa.Column("ip_hash", sa.String(length=64), nullable=True),
        sa.Column("notified", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["proposal_id"], ["proposals.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("proposal_views", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_proposal_views_proposal_id"), ["proposal_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("proposal_views", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_proposal_views_proposal_id"))

    op.drop_table("proposal_views")
    with op.batch_alter_table("proposals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_proposals_share_token"))
        batch_op.drop_index(batch_op.f("ix_proposals_project_id"))

    op.drop_table("proposals")
    with op.batch_alter_table("chat_messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_chat_messages_project_id"))

    op.drop_table("chat_messages")
    with op.batch_alter_table("pvgis_cache", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pvgis_cache_cache_key"))

    op.drop_table("pvgis_cache")
    op.drop_table("projects")
    with op.batch_alter_table("exchange_rate_cache", schema=None) as batch_op:
        batch_op.drop_index("ix_fx_lookup")

    op.drop_table("exchange_rate_cache")
    # ### end Alembic commands ###
