"""Emailing a proposal: compose, claim, send, record.

The composition half is deliberately dull. Every value comes from the frozen
snapshot, the prose around them is a fixed template, and **the language model
writes none of it**. It may write the executive summary *inside* the proposal,
where each number it produces is checked against the snapshot before it is
stored - but an email is sent once, cannot be corrected, and nobody re-reads it
against the figures. So it is generated by code.

The sending half is where the care is. There is no job queue in this
application, so the provider call happens inside the request; what makes that
safe is a database claim, borrowed wholesale from `services/analysis_claim.py`
because the shape of the problem is identical:

1. Insert the delivery row keyed on a deterministic idempotency key, letting
   the UNIQUE index settle any race - the loser re-selects the winner.
2. Take the row with a **conditional UPDATE** to `sending`. `rowcount == 0`
   means somebody else owns it, and no message is composed and no provider is
   called.
3. **Commit before the provider call.** So an ambiguous timeout leaves a
   durable `sending` row rather than nothing at all: the evidence that an
   attempt happened survives the process that made it.
4. Write the terminal status fenced on `status = 'sending'`.

What this buys is *at-least-once with a stable key*, and that is stated rather
than dressed up. A relay that accepts a message and then times out will be
retried, and the customer may receive two copies. Avoiding that needs a
transaction spanning the database and the mail server, which does not exist.
"""

from __future__ import annotations

import hashlib
import logging
from datetime import timedelta
from pathlib import Path
from typing import Any

from jinja2 import Environment, FileSystemLoader, select_autoescape
from sqlalchemy import CursorResult, select, update
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import Settings
from app.core.errors import (
    DeliveryInProgressError,
    EmailProviderUnavailableError,
    EmailSendFailedError,
    EmailSendTimeoutError,
    ProposalAlreadySentError,
    RecipientUnavailableError,
)
from app.domain.customers import mask_email, normalise_email
from app.models.tables import Proposal, ProposalDelivery, ProposalView, _utcnow, as_utc, iso_utc
from app.services import activity
from app.services.email import (
    EmailMessage,
    EmailSendError,
    ProposalEmailSender,
    build_sender,
)

logger = logging.getLogger("solarvis.proposal_email")

TEMPLATE_DIR = Path(__file__).resolve().parents[1] / "templates"

PENDING = "pending"
SENDING = "sending"
SENT = "sent"
FAILED = "failed"

#: How long a `sending` row is treated as genuinely in flight.
#:
#: Past this, a retry may take it. The window is the provider timeout plus room
#: for the surrounding work, so a request that is merely slow is never
#: overtaken by one that assumes it died.
STALE_SEND_MARGIN_SECONDS = 30.0

_environment: Environment | None = None


def environment() -> Environment:
    global _environment
    if _environment is None:
        _environment = Environment(
            loader=FileSystemLoader(str(TEMPLATE_DIR)),
            # On for both parts. A customer's display name is operator-entered
            # free text and reaches the HTML body unmodified.
            autoescape=select_autoescape(default=True, default_for_string=True),
            trim_blocks=True,
            lstrip_blocks=True,
        )
    return _environment


# ---------------------------------------------------------------------------
# Composition
# ---------------------------------------------------------------------------


def recipient_for(proposal: Proposal) -> str:
    """The address this proposal goes to, from its frozen snapshot.

    Read from the snapshot rather than from the live customer record, so a
    recipient the operator confirmed cannot be changed underneath them by an
    edit to the customer between confirming and sending.
    """
    snapshot = proposal.customer_snapshot_json or {}
    raw = snapshot.get("email")
    if not isinstance(raw, str) or not raw.strip():
        raise RecipientUnavailableError(
            "This proposal has no customer, so there is nobody to email it to. "
            "Assign a customer to the project and finalise a new revision."
        )
    try:
        return normalise_email(raw)
    except Exception as error:  # pragma: no cover - stored addresses are normalised
        raise RecipientUnavailableError(
            "The stored customer address is not usable as an email recipient."
        ) from error


def _display_name(proposal: Proposal) -> str:
    snapshot = proposal.customer_snapshot_json or {}
    name = snapshot.get("displayName")
    return name if isinstance(name, str) and name.strip() else "there"


def _money(value: Any) -> str:
    try:
        return f"{float(value):,.0f}"
    except (TypeError, ValueError):  # pragma: no cover - snapshot values are numeric
        return str(value)


def compose(proposal: Proposal, settings: Settings) -> EmailMessage:
    """Render the message. Deterministic, and it sends nothing.

    Called by the preview route as well as the send route, from the same code
    with the same inputs - so what the operator was shown is exactly what goes
    out, rather than a rendering that merely resembles it.
    """
    snapshot = proposal.proposal_data_json or {}
    layout = snapshot.get("layout", {})
    financial = snapshot.get("financial", {})

    context = {
        "customer_name": _display_name(proposal),
        "public_url": f"{settings.web_base_url.rstrip('/')}/proposal/{proposal.share_token}",
        "reference": proposal.reference or proposal.share_token[:8],
        "system_size_kwp": f"{float(proposal.feasible_system_size_kwp):g}",
        "panel_count": proposal.panel_count,
        "annual_production_kwh": f"{float(proposal.annual_production_kwh):,.0f}",
        "annual_savings_eur": _money(
            financial.get("annualSavingsEur", proposal.annual_savings_eur)
        ),
        "capex_eur": _money(financial.get("convertedCapex", {}).get("amount", 0)),
        "payback_years": (
            f"{float(proposal.payback_years):.1f}" if proposal.payback_years else None
        ),
        "capacity_warning": proposal.capacity_warning or layout.get("capacityWarning"),
        "sender_name": settings.email_from_name or "SolarVis",
    }

    env = environment()
    return EmailMessage(
        to=recipient_for(proposal),
        subject=f"Your solar proposal - {context['system_size_kwp']} kWp ({context['reference']})",
        text_body=env.get_template("email/proposal.txt.j2").render(**context),
        html_body=env.get_template("email/proposal.html.j2").render(**context),
        reply_to=settings.email_reply_to or None,
    )


def preview(proposal: Proposal, settings: Settings) -> dict[str, Any]:
    """Everything the operator needs to decide, and nothing that sends.

    The full recipient is included deliberately: this is the confirmation step,
    and confirming a send to a masked address is not confirming anything. The
    masked form travels alongside for every *other* surface - logs, activity
    metadata, the delivery list.

    A proposal with no customer returns a preview with `to: null` rather than
    an error. A preview describes what *would* happen, and "nothing, because
    there is nobody to send to" is one of the answers - refusing here would
    leave the caller with a failed request and no way to explain itself, which
    is exactly the dead end the UI is trying to avoid.
    """
    sender = build_sender(settings)
    ready, reason = sender.available()

    try:
        message: EmailMessage | None = compose(proposal, settings)
    except RecipientUnavailableError:
        message = None

    return {
        "to": message.to if message else None,
        "toMasked": mask_email(message.to) if message else None,
        "subject": message.subject if message else None,
        "textBody": message.text_body if message else None,
        "htmlBody": message.html_body if message else None,
        "publicUrl": f"{settings.web_base_url.rstrip('/')}/proposal/{proposal.share_token}",
        "revisionNumber": proposal.revision_number or 1,
        "reference": proposal.reference,
        "from": settings.email_from or None,
        "fromName": settings.email_from_name,
        "replyTo": settings.email_reply_to or None,
        "provider": sender.name,
        # False for console. The UI reads this to decide between "Send" and
        # "Record locally", so the operator is never told a message left the
        # building when it did not.
        "providerSends": sender.name != "console",
        "providerAvailable": ready,
        "providerDetail": reason,
        "includesPdf": settings.proposal_email_attach_pdf,
    }


# ---------------------------------------------------------------------------
# The claim
# ---------------------------------------------------------------------------


def idempotency_key(proposal: Proposal, recipient: str, *, nonce: str = "") -> str:
    """Deterministic, so every duplicate of one intent computes the same value.

    A double click, a browser refresh mid-send and a client-side retry all
    produce this key, and the UNIQUE index turns three requests into one row.
    A deliberate resend passes a nonce, because that *is* a different intent.
    """
    material = f"{proposal.id}:{recipient}:{proposal.revision_number or 1}:{nonce}"
    return hashlib.sha256(material.encode("utf-8")).hexdigest()[:32]


async def _find_by_key(session: AsyncSession, key: str) -> ProposalDelivery | None:
    return (
        await session.execute(
            select(ProposalDelivery).where(ProposalDelivery.idempotency_key == key)
        )
    ).scalar_one_or_none()


def _is_stale(delivery: ProposalDelivery, settings: Settings) -> bool:
    """Whether a `sending` row has been in flight implausibly long."""
    started = as_utc(delivery.last_attempt_at or delivery.requested_at)
    if started is None:  # pragma: no cover - both columns are always set
        return True
    window = timedelta(seconds=settings.smtp_timeout_seconds + STALE_SEND_MARGIN_SECONDS)
    return (as_utc(_utcnow()) or _utcnow()) - started > window


async def claim(
    session: AsyncSession,
    proposal: Proposal,
    *,
    recipient: str,
    provider: str,
    settings: Settings,
    nonce: str = "",
) -> ProposalDelivery:
    """Take ownership of one send, or refuse.

    Returns a row in `sending`. Raises rather than returning one that somebody
    else owns, so a caller that gets a row here is unambiguously the one that
    may call the provider.
    """
    key = idempotency_key(proposal, recipient, nonce=nonce)

    delivery = await _find_by_key(session, key)
    if delivery is None:
        candidate = ProposalDelivery(
            proposal_id=proposal.id,
            recipient=recipient,
            provider=provider,
            status=PENDING,
            idempotency_key=key,
        )
        try:
            async with session.begin_nested():
                session.add(candidate)
                await session.flush()
            delivery = candidate
        except IntegrityError:
            # Two requests arrived together. The index refused the second, which
            # is the whole point; the loser works with the winner's row.
            logger.info("delivery race on proposal %s; re-selecting the winner", proposal.id)
            delivery = await _find_by_key(session, key)
            if delivery is None:  # pragma: no cover - the constraint guarantees one
                raise

    if delivery.status == SENT:
        raise ProposalAlreadySentError(
            f"This proposal was already sent to {mask_email(delivery.recipient)} on "
            f"{iso_utc(delivery.sent_at)}.",
            details={"deliveryId": delivery.id, "sentAt": iso_utc(delivery.sent_at)},
        )

    takeable = [PENDING, FAILED]
    if delivery.status == SENDING and _is_stale(delivery, settings):
        # The owner is long gone - a process that died, or a request abandoned
        # mid-flight. Reclaimable, and the honest consequence is stated in the
        # docs: if that attempt did reach the relay, this produces a second
        # copy. At-least-once, not exactly-once.
        logger.warning("reclaiming a stale delivery %s for proposal %s", delivery.id, proposal.id)
        takeable.append(SENDING)

    # The conditional UPDATE *is* the lock. Reading the status and then writing
    # it would leave a window two requests can both pass through.
    result: CursorResult[Any] = await session.execute(  # type: ignore[assignment]
        update(ProposalDelivery)
        .where(
            ProposalDelivery.id == delivery.id,
            ProposalDelivery.status.in_(takeable),
        )
        .execution_options(synchronize_session=False)
        .values(
            status=SENDING,
            provider=provider,
            attempt_count=ProposalDelivery.attempt_count + 1,
            last_attempt_at=_utcnow(),
            last_error_code=None,
            last_error_message=None,
        )
    )
    if result.rowcount == 0:
        raise DeliveryInProgressError(
            "This proposal is already being sent. Wait a moment and check its status.",
            details={"deliveryId": delivery.id},
        )

    await session.refresh(delivery)
    return delivery


async def _finish(
    session: AsyncSession,
    delivery: ProposalDelivery,
    **values: Any,
) -> bool:
    """Write a terminal status, fenced on this attempt still owning the row."""
    result: CursorResult[Any] = await session.execute(  # type: ignore[assignment]
        update(ProposalDelivery)
        .where(ProposalDelivery.id == delivery.id, ProposalDelivery.status == SENDING)
        .execution_options(synchronize_session=False)
        .values(**values)
    )
    await session.refresh(delivery)
    return bool(result.rowcount)


async def send(
    session: AsyncSession,
    proposal: Proposal,
    *,
    settings: Settings,
    sender: ProposalEmailSender | None = None,
    nonce: str = "",
    commit: Any = None,
) -> ProposalDelivery:
    """Compose, claim, hand to the provider, record the outcome.

    `commit` is the caller's commit function, invoked *before* the provider
    call. That ordering is the whole reliability story: it makes the `sending`
    row durable, so a process that dies mid-send leaves evidence rather than
    silence.
    """
    if not settings.proposal_email_enabled:
        raise EmailProviderUnavailableError(
            "Proposal email is switched off. The proposal can still be shared by link."
        )

    sender = sender or build_sender(settings)
    ready, reason = sender.available()
    if not ready:
        # Refused before a row moves to `sending`, so a misconfiguration leaves
        # nothing half-claimed to clean up.
        raise EmailProviderUnavailableError(
            f"Email is not configured, so this proposal cannot be sent. {reason or ''}".strip()
        )

    recipient = recipient_for(proposal)
    message = compose(proposal, settings)

    delivery = await claim(
        session,
        proposal,
        recipient=recipient,
        provider=sender.name,
        settings=settings,
        nonce=nonce,
    )

    await activity.record(
        session,
        event_type=activity.PROPOSAL_SEND_REQUESTED,
        actor="user",
        project_id=proposal.project_id,
        proposal_id=proposal.id,
        delivery_id=delivery.id,
        metadata={
            "recipientMasked": mask_email(recipient),
            "revisionNumber": proposal.revision_number or 1,
        },
    )

    if commit is not None:
        await commit(session)

    try:
        result = await sender.send(message)
    except EmailSendError as error:
        await _finish(
            session,
            delivery,
            status=FAILED,
            failed_at=_utcnow(),
            last_error_code=error.code,
            last_error_message=error.detail[:500],
        )
        await activity.record_best_effort(
            session,
            event_type=activity.PROPOSAL_EMAIL_FAILED,
            project_id=proposal.project_id,
            proposal_id=proposal.id,
            delivery_id=delivery.id,
            metadata={
                "recipientMasked": mask_email(recipient),
                "provider": sender.name,
                "errorCode": error.code,
            },
        )
        if commit is not None:
            await commit(session)

        logger.warning(
            "delivery %s failed for %s: %s", delivery.id, mask_email(recipient), error.code
        )
        if error.code == "EMAIL_SEND_TIMEOUT":
            raise EmailSendTimeoutError(
                "The mail server did not respond in time, so it is not known whether the "
                "proposal was sent. Check the delivery status before retrying.",
                details={"deliveryId": delivery.id},
            ) from error
        if error.code == "EMAIL_PROVIDER_UNAVAILABLE":
            raise EmailProviderUnavailableError(error.detail) from error
        raise EmailSendFailedError(
            error.detail or "The proposal could not be emailed.",
            details={"deliveryId": delivery.id},
        ) from error

    await _finish(
        session,
        delivery,
        status=SENT,
        sent_at=result.accepted_at,
        provider=result.provider,
        provider_message_id=result.provider_message_id,
        last_error_code=None,
        last_error_message=None,
    )
    await activity.record_best_effort(
        session,
        event_type=activity.PROPOSAL_EMAIL_SENT,
        actor="user",
        project_id=proposal.project_id,
        proposal_id=proposal.id,
        delivery_id=delivery.id,
        metadata={
            "recipientMasked": mask_email(recipient),
            "provider": result.provider,
            "revisionNumber": proposal.revision_number or 1,
        },
    )

    logger.info(
        "delivery %s %s via %s to %s",
        delivery.id,
        "recorded" if not result.delivered_to_provider else "accepted",
        result.provider,
        mask_email(recipient),
    )
    return delivery


async def notify_opened(
    session: AsyncSession,
    proposal: Proposal,
    *,
    view_id: str,
    view_count: int,
    settings: Settings,
    sender: ProposalEmailSender | None = None,
) -> bool:
    """Tell the salesperson their proposal was opened. Best-effort, always.

    The brief's bonus asks for a console *or* email notification on open; this
    is both, through the same provider as everything else, so console mode
    prints it and SMTP mode sends it.

    Guarded by `proposal_views.notified`, a column that has existed and been
    written by nothing since the first migration. Setting it here is what makes
    the notification fire once per counted view rather than once per request -
    and the flag is per view row, so it cannot suppress a genuinely new opening.

    Every failure is swallowed. A notification is for the operator; the
    customer is *currently looking at the page*, and nothing about their view
    may depend on an outbound email succeeding.
    """
    recipient = settings.salesperson_email.strip()
    if not recipient:
        return False

    view = await session.get(ProposalView, view_id)
    if view is None or view.notified:
        return False

    try:
        sender = sender or build_sender(settings)
        ready, _ = sender.available()
        if not ready:
            return False

        name = _display_name(proposal)
        url = f"{settings.web_base_url.rstrip('/')}/proposal/{proposal.share_token}"
        await sender.send(
            EmailMessage(
                to=recipient,
                subject=f"Proposal opened - {proposal.reference or proposal.share_token[:8]}",
                # The shape the case brief prints for the console notification,
                # kept verbatim so the two modes say the same thing.
                text_body=(
                    f"[Proposal Viewed]\n"
                    f"  Proposal:   {proposal.reference or proposal.share_token[:12]}\n"
                    f"  Customer:   {name}\n"
                    f"  Opened at:  {iso_utc(_utcnow())}\n"
                    f"  View count: {view_count}\n"
                    f"  Link:       {url}\n\n"
                    f"This is a view of the proposal page, not an email open - there is no "
                    f"open tracking in this system.\n"
                ),
            )
        )
        view.notified = True
        await session.flush()
        return True
    except Exception:
        logger.exception("open notification failed for %s; continuing", proposal.share_token[:8])
        return False


async def history(session: AsyncSession, proposal: Proposal) -> list[ProposalDelivery]:
    rows = (
        await session.execute(
            select(ProposalDelivery)
            .where(ProposalDelivery.proposal_id == proposal.id)
            .order_by(ProposalDelivery.requested_at.desc(), ProposalDelivery.id.desc())
        )
    ).scalars()
    return list(rows)


def serialise(delivery: ProposalDelivery) -> dict[str, Any]:
    """The delivery as the operator sees it.

    The recipient is **masked**. The full address is shown once, at the
    confirmation step, where the operator is deciding; a status list does not
    need it, and every surface that carries it is another place it leaks from.
    """
    return {
        "deliveryId": delivery.id,
        "proposalId": delivery.proposal_id,
        "channel": delivery.channel,
        "recipientMasked": mask_email(delivery.recipient),
        "status": delivery.status,
        "provider": delivery.provider,
        # The single field that keeps console mode honest downstream.
        "providerSends": delivery.provider != "console",
        "attemptCount": delivery.attempt_count,
        "errorCode": delivery.last_error_code,
        "errorMessage": delivery.last_error_message,
        "requestedAt": iso_utc(delivery.requested_at),
        "lastAttemptAt": iso_utc(delivery.last_attempt_at),
        "sentAt": iso_utc(delivery.sent_at),
        "failedAt": iso_utc(delivery.failed_at),
    }


__all__ = [
    "FAILED",
    "PENDING",
    "SENDING",
    "SENT",
    "claim",
    "compose",
    "history",
    "idempotency_key",
    "preview",
    "recipient_for",
    "send",
    "serialise",
]
